name: test-action-goland
on: push
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - name: Cryptosoft-SBOM-generator.
        id: Cryptosoft-SBOM-generator
        uses: CryptosoftInc/dependencyTrack@1.0.0
        with:
          dt-url:  "https://dt-api.staging.cryptosoft.com/api/v1/bom"
          api-key: '1DMIXAnGtTIeTQDddlHSvpj6d3as174S '
          project-name: "test-golang"
          project-version: "1.11"
          parent-name: "cs-backend"
          parent-version: "1.1.0"
