name: test-action-javascript
on: push
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
      - name: Cryptosoft-SBOM-generator.
        id: Cryptosoft-SBOM-generator
        uses: CryptosoftInc/Dependency-Track@1.0.0
        with:
          dt-url:  "https://dt-api-test-action.staging.cryptosoft.com/api/v1/bom"
          api-key: 'npPRzyVPC59PSlVe52ZIBYIuhZhF2bBN '
          project-name: "test-actioreact"
          project-version: "1.21"
